#!/bin/bash

echo Getting ready!

sudo apt-get update
sudo apt-get upgrade

sleep 5s

sudo apt-get install vim 

echo installing vimplug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt-get install curl

sudo apt-get install rofi

sudo apt-get install compton

sudo apt-get install dunst

sudo apt-get install feh

sudo apt-get install cmus

sudo apt-get install arandr

sudo apt-get install exiftool

sudo apt-get install tty-clock 

sudo snap install taskbook

sudo apt-get install mpv 

sudo apt-get install clamav 

sudo apt-get install clamtk 

sudo apt-get install neofetch

sudo apt-get install ranger

sudo apt-get install zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

sudo apt-get install fonts-powerline

sudo apt-get install nodejs

sudo apt-get install npm

sudo npm install -g create-react-app

sudo npm install -g prettier

echo speedRicer ppa
sudo add-apt-repository -y ppa:kgilmer/speed-ricer

sudo apt-get update

echo installing i3-gaps
sudo apt-get install i3-gaps

echo installing polybar
sudo apt-get install polybar

echo isntalling pywal
sudo apt-get install pywal

echo Dont forget to run ranger --copy-config=all then add config files
echo Done!!
