#!/bin/bash

echo Getting ready!

sudo apt-get update
sudo apt-get upgrade
sleep 5s

sudo apt-get install vim 

echo installing vimplug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt-get install git

sudo apt-get install curl

sudo apt-get install i3blocks

sudo apt-get install rofi

sudo apt-get install compton

sudo apt-get install dunst

sudo apt-get install feh

sudo apt-get install cmus

sudo apt-get install arandr

sudo apt-get install rxvt-unicodsude

sudo apt-get install exiftool

sudo apt-get install tty-clock 

sudo snap install taskbook

sudo apt-get install mpv 

sudo apt-get install clamav 

sudo apt-get install clamtk 

sudo apt-get install neofetch

sudo apt-get install ranger

sudo apt-get install nodejs

sudo apt-get install npm

sudo npm install -g create-react-app

sudo npm install -g prettier
